"""empty message

Revision ID: 257b3b19c005
Revises: 93c4140c9b1f
Create Date: 2023-03-30 13:39:58.188261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257b3b19c005'
down_revision = '93c4140c9b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
